-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    stages: [commit, push]
    hooks:
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-merge-conflict
