-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 2c62e4aafc6708f7bdc5536670726729724445c8
    stages:
    - commit
    - push
    hooks:
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-merge-conflict
